// Code generated by girgen. DO NOT EDIT.

package secret

// #include <stdlib.h>
// #include <libsecret/secret.h>
import "C"

// MAJOR_VERSION: major version of libsecret.
const MAJOR_VERSION = 0

// MICRO_VERSION: micro version of libsecret.
const MICRO_VERSION = 4

// MINOR_VERSION: minor version of libsecret.
const MINOR_VERSION = 20
