// Code generated by girgen. DO NOT EDIT.

package secret

// #cgo pkg-config: libsecret-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <libsecret/secret.h>
import "C"

const BACKEND_EXTENSION_POINT_NAME = "secret-backend"
