// Code generated by girgen. DO NOT EDIT.

package secret

import (
	"github.com/diamondburned/gotk4/pkg/glib/v2"
)

// #cgo pkg-config: libsecret-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <libsecret/secret.h>
import "C"

func ErrorGetQuark() glib.Quark {
	var _cret C.GQuark // in

	_cret = C.secret_error_get_quark()

	var _quark glib.Quark // out

	_quark = uint32(_cret)

	return _quark
}
