// Code generated by girgen. DO NOT EDIT.

package secret

import (
	"context"
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/core/gcancel"
	"github.com/diamondburned/gotk4/pkg/core/gerror"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gio/v2"
	"github.com/diamondburned/gotk4/pkg/glib/v2"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <libsecret/secret.h>
// extern void _gotk4_gio2_AsyncReadyCallback(GObject*, GAsyncResult*, gpointer);
import "C"

// glib.Type values for secret-prompt.go.
var GTypePrompt = externglib.Type(C.secret_prompt_get_type())

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: GTypePrompt, F: marshalPrompt},
	})
}

// PromptOverrider contains methods that are overridable.
type PromptOverrider interface {
}

// Prompt: proxy object representing a prompt that the Secret Service will
// display to the user.
type Prompt struct {
	_ [0]func() // equal guard
	gio.DBusProxy
}

var (
	_ externglib.Objector = (*Prompt)(nil)
)

func classInitPrompter(gclassPtr, data C.gpointer) {
	C.g_type_class_add_private(gclassPtr, C.gsize(unsafe.Sizeof(uintptr(0))))

	goffset := C.g_type_class_get_instance_private_offset(gclassPtr)
	*(*C.gpointer)(unsafe.Add(unsafe.Pointer(gclassPtr), goffset)) = data

}

func wrapPrompt(obj *externglib.Object) *Prompt {
	return &Prompt{
		DBusProxy: gio.DBusProxy{
			Object: obj,
			AsyncInitable: gio.AsyncInitable{
				Object: obj,
			},
			DBusInterface: gio.DBusInterface{
				Object: obj,
			},
			Initable: gio.Initable{
				Object: obj,
			},
		},
	}
}

func marshalPrompt(p uintptr) (interface{}, error) {
	return wrapPrompt(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// Perform runs a prompt and performs the prompting. Returns TRUE if the prompt
// was completed and not dismissed.
//
// If window_id is non-null then it is used as an XWindow id on Linux. The API
// expects this id to be converted to a string using the <literal>d</literal>
// printf format. The Secret Service can make its prompt transient for the
// window with this id. In some Secret Service implementations this is not
// possible, so the behavior depending on this should degrade gracefully.
//
// This method will return immediately and complete asynchronously.
//
// The function takes the following parameters:
//
//    - ctx (optional): optional cancellation object.
//    - windowId (optional): string form of XWindow id for parent window to be
//      transient for.
//    - returnType: variant type of the prompt result.
//    - callback (optional): called when the operation completes.
//
func (self *Prompt) Perform(ctx context.Context, windowId string, returnType *glib.VariantType, callback gio.AsyncReadyCallback) {
	var _arg0 *C.SecretPrompt       // out
	var _arg3 *C.GCancellable       // out
	var _arg1 *C.gchar              // out
	var _arg2 *C.GVariantType       // out
	var _arg4 C.GAsyncReadyCallback // out
	var _arg5 C.gpointer

	_arg0 = (*C.SecretPrompt)(unsafe.Pointer(externglib.InternObject(self).Native()))
	{
		cancellable := gcancel.GCancellableFromContext(ctx)
		defer runtime.KeepAlive(cancellable)
		_arg3 = (*C.GCancellable)(unsafe.Pointer(cancellable.Native()))
	}
	if windowId != "" {
		_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(windowId)))
		defer C.free(unsafe.Pointer(_arg1))
	}
	_arg2 = (*C.GVariantType)(gextras.StructNative(unsafe.Pointer(returnType)))
	if callback != nil {
		_arg4 = (*[0]byte)(C._gotk4_gio2_AsyncReadyCallback)
		_arg5 = C.gpointer(gbox.AssignOnce(callback))
	}

	C.secret_prompt_perform(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5)
	runtime.KeepAlive(self)
	runtime.KeepAlive(ctx)
	runtime.KeepAlive(windowId)
	runtime.KeepAlive(returnType)
	runtime.KeepAlive(callback)
}

// PerformFinish: complete asynchronous operation to run a prompt and perform
// the prompting.
//
// Returns a variant result if the prompt was completed and not dismissed. The
// type of result depends on the action the prompt is completing, and is defined
// in the Secret Service DBus API specification.
//
// The function takes the following parameters:
//
//    - result asynchronous result passed to the callback.
//
// The function returns the following values:
//
//    - variant: NULL if the prompt was dismissed or an error occurred, a variant
//      result if the prompt was successful.
//
func (self *Prompt) PerformFinish(result gio.AsyncResulter) (*glib.Variant, error) {
	var _arg0 *C.SecretPrompt // out
	var _arg1 *C.GAsyncResult // out
	var _cret *C.GVariant     // in
	var _cerr *C.GError       // in

	_arg0 = (*C.SecretPrompt)(unsafe.Pointer(externglib.InternObject(self).Native()))
	_arg1 = (*C.GAsyncResult)(unsafe.Pointer(externglib.InternObject(result).Native()))

	_cret = C.secret_prompt_perform_finish(_arg0, _arg1, &_cerr)
	runtime.KeepAlive(self)
	runtime.KeepAlive(result)

	var _variant *glib.Variant // out
	var _goerr error           // out

	_variant = (*glib.Variant)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_variant)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.g_variant_unref((*C.GVariant)(intern.C))
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _variant, _goerr
}

// PerformSync runs a prompt and performs the prompting. Returns a variant
// result if the prompt was completed and not dismissed. The type of result
// depends on the action the prompt is completing, and is defined in the Secret
// Service DBus API specification.
//
// If window_id is non-null then it is used as an XWindow id on Linux. The API
// expects this id to be converted to a string using the <literal>d</literal>
// printf format. The Secret Service can make its prompt transient for the
// window with this id. In some Secret Service implementations this is not
// possible, so the behavior depending on this should degrade gracefully.
//
// This method may block indefinitely and should not be used in user interface
// threads.
//
// The function takes the following parameters:
//
//    - ctx (optional): optional cancellation object.
//    - windowId (optional): string form of XWindow id for parent window to be
//      transient for.
//    - returnType: variant type of the prompt result.
//
// The function returns the following values:
//
//    - variant: NULL if the prompt was dismissed or an error occurred.
//
func (self *Prompt) PerformSync(ctx context.Context, windowId string, returnType *glib.VariantType) (*glib.Variant, error) {
	var _arg0 *C.SecretPrompt // out
	var _arg2 *C.GCancellable // out
	var _arg1 *C.gchar        // out
	var _arg3 *C.GVariantType // out
	var _cret *C.GVariant     // in
	var _cerr *C.GError       // in

	_arg0 = (*C.SecretPrompt)(unsafe.Pointer(externglib.InternObject(self).Native()))
	{
		cancellable := gcancel.GCancellableFromContext(ctx)
		defer runtime.KeepAlive(cancellable)
		_arg2 = (*C.GCancellable)(unsafe.Pointer(cancellable.Native()))
	}
	if windowId != "" {
		_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(windowId)))
		defer C.free(unsafe.Pointer(_arg1))
	}
	_arg3 = (*C.GVariantType)(gextras.StructNative(unsafe.Pointer(returnType)))

	_cret = C.secret_prompt_perform_sync(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(self)
	runtime.KeepAlive(ctx)
	runtime.KeepAlive(windowId)
	runtime.KeepAlive(returnType)

	var _variant *glib.Variant // out
	var _goerr error           // out

	_variant = (*glib.Variant)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_variant)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.g_variant_unref((*C.GVariant)(intern.C))
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _variant, _goerr
}

// Run runs a prompt and performs the prompting. Returns a variant result if the
// prompt was completed and not dismissed. The type of result depends on the
// action the prompt is completing, and is defined in the Secret Service DBus
// API specification.
//
// If window_id is non-null then it is used as an XWindow id on Linux. The API
// expects this id to be converted to a string using the <literal>d</literal>
// printf format. The Secret Service can make its prompt transient for the
// window with this id. In some Secret Service implementations this is not
// possible, so the behavior depending on this should degrade gracefully.
//
// This runs the dialog in a recursive mainloop. When run from a user interface
// thread, this means the user interface will remain responsive. Care should be
// taken that appropriate user interface actions are disabled while running the
// prompt.
//
// The function takes the following parameters:
//
//    - ctx (optional): optional cancellation object.
//    - windowId (optional): string form of XWindow id for parent window to be
//      transient for.
//    - returnType: variant type of the prompt result.
//
// The function returns the following values:
//
//    - variant: NULL if the prompt was dismissed or an error occurred.
//
func (self *Prompt) Run(ctx context.Context, windowId string, returnType *glib.VariantType) (*glib.Variant, error) {
	var _arg0 *C.SecretPrompt // out
	var _arg2 *C.GCancellable // out
	var _arg1 *C.gchar        // out
	var _arg3 *C.GVariantType // out
	var _cret *C.GVariant     // in
	var _cerr *C.GError       // in

	_arg0 = (*C.SecretPrompt)(unsafe.Pointer(externglib.InternObject(self).Native()))
	{
		cancellable := gcancel.GCancellableFromContext(ctx)
		defer runtime.KeepAlive(cancellable)
		_arg2 = (*C.GCancellable)(unsafe.Pointer(cancellable.Native()))
	}
	if windowId != "" {
		_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(windowId)))
		defer C.free(unsafe.Pointer(_arg1))
	}
	_arg3 = (*C.GVariantType)(gextras.StructNative(unsafe.Pointer(returnType)))

	_cret = C.secret_prompt_run(_arg0, _arg1, _arg2, _arg3, &_cerr)
	runtime.KeepAlive(self)
	runtime.KeepAlive(ctx)
	runtime.KeepAlive(windowId)
	runtime.KeepAlive(returnType)

	var _variant *glib.Variant // out
	var _goerr error           // out

	_variant = (*glib.Variant)(gextras.NewStructNative(unsafe.Pointer(_cret)))
	runtime.SetFinalizer(
		gextras.StructIntern(unsafe.Pointer(_variant)),
		func(intern *struct{ C unsafe.Pointer }) {
			C.g_variant_unref((*C.GVariant)(intern.C))
		},
	)
	if _cerr != nil {
		_goerr = gerror.Take(unsafe.Pointer(_cerr))
	}

	return _variant, _goerr
}
